/*
Auto-generated by: https://github.com
Modified for static assets.
*/

import React from "react";
import { useGLTF, useTexture, Decal } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/shirt_baked.glb");

  // Load the static logo image from your public folder
  const logoTexture = useTexture("/threejs.png");

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.T_Shirt_male.geometry}>
        {/* Swapping the default material for a dynamic one with a static color */}
        <meshStandardMaterial
          color="#3b82f6" // Your static hex color (e.g., nice blue)
          roughness={0.6}
        />

        {/* Placing the logo onto the front center chest of the shirt */}
        <Decal
          position={[0, 0.04, 0.15]} // X, Y, Z positioning on the mesh surface
          rotation={[0, 0, 0]} // Keeps the logo upright
          scale={0.15} // Controls the logo dimensions
          map={logoTexture}
          depthWrite={true} // Prevents the logo from mirroring onto the back
        />
      </mesh>
    </group>
  );
}

useGLTF.preload("/shirt_baked.glb");
