/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Glbs/HODIES SHIRTS.glb 
*/

import React from 'react'
import { useGLTF, useTexture, Decal } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Glbs/HODIES SHIRTS.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloth_mesh.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_5.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_6.geometry} material={materials['FABRIC 2_2562']} />
    </group>
  )
}

useGLTF.preload('/HODIES SHIRTS.glb')
