/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Glbs/HODIES.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Glbs/HODIES.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloth_mesh.geometry} material={materials['FABRIC 1_30401']} />
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials['FABRIC 1_30401']} />
      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials['FABRIC 1_30401']} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials['FABRIC 1_30401']} />
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials['FABRIC 1_30401']} />
      <mesh geometry={nodes.Cloth_mesh_5.geometry} material={materials['FABRIC 1_30401']} />
      <mesh geometry={nodes.Cloth_mesh_6.geometry} material={materials['FABRIC 1_30401']} />
      <mesh geometry={nodes.Cloth_mesh_7.geometry} material={materials['FABRIC 1_30401']} />
      <mesh geometry={nodes.Cloth_mesh_8.geometry} material={materials['FABRIC 1_30401']} />
      <mesh geometry={nodes.Cloth_mesh_9.geometry} material={materials['FABRIC 1_30401']} />
      <mesh geometry={nodes.Cloth_mesh_10.geometry} material={materials['FABRIC 1_30401']} />
    </group>
  )
}

useGLTF.preload('/HODIES.glb')
