/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Glbs/POLO SHIRTS.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Glbs/POLO SHIRTS.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloth_mesh.geometry} material={materials['FABRIC 1_2562']} />
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials['FABRIC 1_2562']} />
      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials['FABRIC 1_2562']} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials['FABRIC 1_2562']} />
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials['Default Buttonhole_2568']} />
      <mesh geometry={nodes.Cloth_mesh_5.geometry} material={materials['Default Buttonhole_2568']} />
      <mesh geometry={nodes.Cloth_mesh_6.geometry} material={materials['Default Buttonhole_2568']} />
      <mesh geometry={nodes.Cloth_mesh_7.geometry} material={materials['FABRIC 1_2562']} />
      <mesh geometry={nodes.Cloth_mesh_8.geometry} material={materials['FABRIC 1_2562']} />
      <mesh geometry={nodes.Cloth_mesh_9.geometry} material={materials['FABRIC 1_2562']} />
      <mesh geometry={nodes.Cloth_mesh_10.geometry} material={materials['FABRIC 1_2562']} />
      <group position={[0.003, 1.51, 0.082]} rotation={[1.21, 0.073, -0.121]} scale={[0.7, 1, 0.7]}>
        <mesh geometry={nodes.Button_326452.geometry} material={materials['Default Button_2564']} />
        <mesh geometry={nodes.Button_326452_1.geometry} material={materials['Default Button_2564']} />
      </group>
      <group position={[0.003, 1.55, 0.064]} rotation={[1.134, 0.169, -0.336]} scale={[0.7, 1, 0.7]}>
        <mesh geometry={nodes.Button_326483.geometry} material={materials['Default Button_2564']} />
        <mesh geometry={nodes.Button_326483_1.geometry} material={materials['Default Button_2564']} />
      </group>
      <group position={[0.005, 1.59, 0.042]} rotation={[0.897, -0.328, -0.5]} scale={[0.7, 1, 0.7]}>
        <mesh geometry={nodes.Button_326515.geometry} material={materials['Default Button_2564']} />
        <mesh geometry={nodes.Button_326515_1.geometry} material={materials['Default Button_2564']} />
      </group>
    </group>
  )
}

useGLTF.preload('/POLO SHIRTS.glb')
