/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Glbs/PULL OVER LONG SLEEVES.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Glbs/PULL OVER LONG SLEEVES.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cloth_mesh.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_1.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_2.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_3.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_4.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_5.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_6.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_7.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_8.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_9.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_10.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_11.geometry} material={materials['FABRIC 2_2562']} />
      <mesh geometry={nodes.Cloth_mesh_12.geometry} material={materials['Zipper 10_TapeFabric_41643']} />
      <mesh geometry={nodes.Cloth_mesh_13.geometry} material={materials['Zipper 10_Teeth_41668']} />
      <mesh geometry={nodes.Cloth_mesh_14.geometry} material={materials['Zipper 10_TapeFabric_41643']} />
      <mesh geometry={nodes.Cloth_mesh_15.geometry} material={materials['Zipper 10_Teeth_41668']} />
      <mesh geometry={nodes.Zipper_1_2.geometry} material={materials['Zipper 10_TopStopper_41752']} position={[0.001, 1.649, 0.059]} rotation={[0.249, 0.002, -0.033]} />
      <mesh geometry={nodes.Zipper_1_3.geometry} material={materials['Zipper 10_TopStopper_41764']} position={[0.001, 1.649, 0.059]} rotation={[0.248, 0.08, -0.039]} />
      <mesh geometry={nodes.Zipper_1_4.geometry} material={materials['Zipper 10_BottomStopper_41790']} position={[-0.004, 0.961, 0.121]} rotation={[-0.165, -0.09, -0.215]} />
      <mesh geometry={nodes.Zipper_1_5.geometry} material={materials['Zipper 10_BottomStopper_41803']} position={[-0.004, 0.961, 0.121]} rotation={[-0.165, -0.045, -0.102]} />
      <mesh geometry={nodes.Zipper_1.geometry} material={materials['Zipper 10_Slider_41702']} position={[0.001, 1.642, 0.057]} rotation={[0.249, 0.002, -0.033]}>
        <mesh geometry={nodes.Zipper_1_1.geometry} material={materials['Zipper 10_Puller_41727']} position={[0, 0, 0.003]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/PULL OVER LONG SLEEVES.glb')
