/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Glbs/SLEEVELESS HODIES.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF("/Glbs/SLEEVELESS HODIES.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cloth_mesh.geometry}
        material={materials["FABRIC 1_39604"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_1.geometry}
        material={materials["FABRIC 1_39604"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_2.geometry}
        material={materials["FABRIC 1_39604"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_3.geometry}
        material={materials["FABRIC 1_39604"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_4.geometry}
        material={materials["FABRIC 1_39604"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_5.geometry}
        material={materials["FABRIC 1_39604"]}
      />
      <mesh
        geometry={nodes.Cloth_mesh_6.geometry}
        material={materials["FABRIC 1_39604"]}
      />
    </group>
  );
}

useGLTF.preload('/SLEEVELESS HODIES.glb')
